# Site settings
title: "HTTP/2 Dashboard"
email: matteo.varvello@telefonica.com
description: > # this means to ignore newlines until "baseurl:"
  Monitoring the adoption and performance of HTTP/2 on the Web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://isthewebhttp2yet.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
